[workspace]
members  = [ "crates/ffi", "crates/nixon", "crates/wasm" ]
exclude  = [ "benchmarks", "fuzz" ]
resolver = "3"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code  = "forbid"

[workspace.lints.clippy]
correctness = "deny"
suspicious  = "warn"
style       = "warn"
complexity  = "warn"
perf        = "warn"

[profile.release]
codegen-units = 1
lto           = "fat"
opt-level     = 3
panic         = "abort"
strip         = true

[profile.bench]
debug    = true
inherits = "release"
strip    = false
