[package]
name         = "nixon-benchmarks"
version      = "0.0.0"
edition      = "2024"
rust-version = "1.97"
publish      = false
license      = "GPL-3.0-only"

# fwiw we cannot really build those with Nix. That's sad, but also, not really
# because we probably won't be benchmarking with Nix anyway.
[dependencies]
nixel = { git = "https://github.com/kamadorueda/nixel", rev = "a4d7ccfd2a5ce28b6ffdc2ed0dd3f6c339b2357f", default-features = false }
nixon = { path = "../crates/nixon" }
rnix  = { git = "https://github.com/nix-community/rnix-parser", rev = "aae4163d88efefcba5e11482f25a5e6dcd21492c" }

[dev-dependencies]
criterion = { version = "0.8.2", default-features = false }

[[bench]]
harness = false
name    = "parse"

[profile.release]
codegen-units = 1
lto           = "fat"
opt-level     = 3
strip         = true

[profile.bench]
debug    = true
inherits = "release"
strip    = false
